###
### name: דוד בורג
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: 1
### date: 19/05/2025
### 
### ניתונים של מחלת הכורה בלונדון מ-1854
###
### source: https://arxiv.org/html/2504.13970v1


# Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

## Load required packages
```{r load-packages, include false}  
options("install.lock" = FALSE,
        "repos" = c(CRAN = "https://cloud.r-project.org")) # Replace with your target repo URL
if (!require("pacman")) install.packages("pacman") ; library(pacman)
library(pacman)
pacman::p_load(SnowData,
              sf,       
              plotly,
              gtsummary,
              dplyr,    
              osmdata
            )
```

# Get data
```{r load data, include false}
# List all objects (variables) in SnowData
ls("package:SnowData")

# Load the data from John Snow package
data(cholera_cases)
data(pump_locations)
print(cholera_cases)
print(pump_locations)
```

# transform spatial data
```{r load data, include false}
# Define BBOX in EPSG:27700 and transform to EPSG:4326 for OSM
soho_bbox_27700 <- st_bbox(c(xmin = 529150.0, ymin = 180720.6,
                             xmax = 529750.9, ymax = 181370.5),
                           crs = st_crs(27700))
soho_bbox_4326 <- st_bbox(st_transform(st_as_sfc(soho_bbox_27700), crs = 4326))

# Get OSM data and transform to EPSG:27700
streets <- opq(bbox = soho_bbox_4326) %>%
  add_osm_feature(key = "highway") %>%
  osmdata_sf()
streets <- st_transform(streets$osm_lines, crs = 27700)

# Convert cholera cases and pump locations to sf
cholera_sf <- st_as_sf(cholera_cases, coords = c("Easting", "Northing"), crs = 27700)
pumps_sf <- st_as_sf(pump_locations, coords = c("Easting", "Northing"), crs = 27700)

# Convert sf to data frame with coordinates for Plotly
cholera_coords <- cholera_sf %>%
  mutate(lon = st_coordinates(.)[,1],
         lat = st_coordinates(.)[,2]) %>%
  st_drop_geometry()

pumps_coords <- pumps_sf %>%
  mutate(lon = st_coordinates(.)[,1],
         lat = st_coordinates(.)[,2]) %>%
  st_drop_geometry()
```

# Plot cholera cases and pump locations
```{r load data, include false}
fig1 <- plot_ly() %>%
  add_markers(data = cholera_coords, x = ~lon, y = ~lat,
              type = 'scatter', mode = 'markers',
              marker = list(color = 'red', size = 5, opacity = 0.6),
              name = 'Cholera Cases') %>%
  add_markers(data = pumps_coords, x = ~lon, y = ~lat,
              type = 'scatter', mode = 'markers',
              marker = list(color = 'blue', size = 10, symbol = "triangle-up"),
              name = 'Water Pumps') %>%
  layout(title = "John Snow’s 1854 Cholera Map",
         xaxis = list(title = "East"),
         yaxis = list(title = "North"))

fig1
```


# add streets
```{r do_T_test, include false}
# Convert street geometries to coordinates
street_coords <- streets %>%
  st_coordinates() %>%
  as_tibble() %>%
  rename(lon = X, lat = Y) %>%
  mutate(group = L1)

# Plot with streets
fig2 <- plot_ly() %>%
  add_lines(data = street_coords, x = ~lon, y = ~lat,
            split = ~group,
            line = list(color = 'gray', width = 0.5),
            name = "Streets",
              showlegend = FALSE) %>%
  add_markers(data = cholera_coords, x = ~lon, y = ~lat,
              marker = list(color = 'red', size = 5, opacity = 0.6),
              name = "Cholera Cases",
              showlegend = FALSE) %>%
  add_markers(data = pumps_coords, x = ~lon, y = ~lat,
              marker = list(color = 'blue', size = 10, symbol = "triangle-up"),
              name = "Water Pumps",
              showlegend = FALSE) %>%
  layout(title = "Cholera Deaths, Pumps & Streets",
         xaxis = list(title = "East"),
         yaxis = list(title = "North"))
         
fig2
```


# add distance to pumps
```{r distances, include false}
# Calculate nearest pump for each cholera case
cholera_sf$nearest_pump <- st_nearest_feature(cholera_sf, pumps_sf)

# Create sf LINESTRING for each connection
connections_sf <- mapply(function(case_geom, pump_geom) {
  st_linestring(rbind(st_coordinates(case_geom), st_coordinates(pump_geom)))
}, st_geometry(cholera_sf), st_geometry(pumps_sf[cholera_sf$nearest_pump, ]), SIMPLIFY = FALSE)

connections_sf <- st_sfc(connections_sf, crs = 27700)
connections_sf <- st_sf(geometry = connections_sf)

# Add pump ID to the connections
connections_sf$pump_id <- as.factor(cholera_sf$nearest_pump)

# Extract coordinates and include cluster info
conn_coords <- st_coordinates(connections_sf) %>%
  as_tibble() %>%
  rename(lon = X, lat = Y) %>%
  mutate(group = L1) %>%
  left_join(tibble(group = 1:nrow(connections_sf),
                   pump_id = connections_sf$pump_id),
            by = "group")


fig_clustered <- plot_ly() %>%
  add_lines(data = street_coords, x = ~lon, y = ~lat,
            split = ~group,
            line = list(color = 'gray', width = 0.5),
            showlegend = FALSE) %>%
  add_lines(data = conn_coords, x = ~lon, y = ~lat,
            split = ~group, color = ~pump_id,
            line = list(width = 0.8),
            showlegend = FALSE) %>%
  add_markers(data = cholera_coords, x = ~lon, y = ~lat,
              marker = list(color = 'black', size = 4, opacity = 0.8),
              showlegend = FALSE) %>%
  add_markers(data = pumps_coords, x = ~lon, y = ~lat,
              marker = list(color = 'red', size = 8, symbol = "star"),
              showlegend = FALSE) %>%
  layout(title = "Cholera Cases Connected to Nearest Pump Clusters",
         xaxis = list(title = "East"),
         yaxis = list(title = "North"))

fig_clustered
```